[package]
name = "rtrtr"
version = "0.1.0"
edition = "2018"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
description = "The RPKI Data Express Mail Service"
repository = "https://github.com/NLnetLabs/rtrtr"
keywords = ["rpki", "routing-security", "bgp"]
license = "BSD-3-Clause"
readme = "README.md"

[dependencies]
clap = "2.33"
futures = "0.3"
log = "0.4"
rand = "0.7.3"
rpki-rtr = { git = "https://github.com/NLnetLabs/rpki-rtr", branch = "stepped-client" }
serde = "1.0"
serde_derive = "1.0"
slab = "0.4.2"
simple-logging = "2.0.2"
tokio	  = { version="0.2", features=["dns", "io-util", "macros", "rt-core", "rt-threaded", "stream", "sync", "tcp", "time"]}
toml = "0.5.6"
