[package]
name = "rtrtr"
version = "0.1.3-dev"
edition = "2018"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
description = "A versatile tool for managing route filters"
repository = "https://github.com/NLnetLabs/rtrtr"
keywords = ["rpki", "routing-security", "bgp"]
license = "BSD-3-Clause"
readme = "README.md"

[dependencies]
arc-swap	= "1.0"
chrono          = "0.4.11"
clap            = "2.33"
crossbeam-utils = "0.8.4"
fern            = "0.6.0"
futures         = "0.3"
hyper           = { version = "0.14.8", features = [ "server", "stream" ] }
log             = "0.4"
log-reroute     = "0.1.5"
rand            = "0.8.3"
reqwest		= { version = "0.11.3", default-features = false, features = ["blocking", "rustls-tls"] }
rpki    	= { version = "0.11.0", features = ["rtr"] }
serde           = { version = "1.0", features = ["derive"] }
serde_json      = "1.0"
slab            = "0.4.2"
simple-logging  = "2.0.2"
tokio	        = { version = "1.6", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"]}
tokio-stream    = { version = "0.1", features = ["net"] }
toml            = "0.5.6"
url		= { version = "2.2", features = ["serde"] }

[target.'cfg(unix)'.dependencies]
libc            = "0.2.68"
syslog          = "5.0.0"

[profile.release]
panic = "abort"

[package.metadata.deb]
name = "rtrtr"
maintainer = "The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"
license-file = ["LICENSE", "0"]
extended-description = """\
RTRTR is an RPKI data proxy, designed to collect Validated ROA Payloads \
from one or more sources in multiple formats and dispatch it onwards. It \
provides the means to implement multiple distribution architectures for RPKI \
such as centralised RPKI validators that dispatch data to local caching RTR \
servers. """
depends = "$auto, adduser"
section = "net"
priority = "optional"
assets = [
    ["target/release/rtrtr", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/rtrtr/", "644"],
    ["etc/rtrtr.conf.system-service", "etc/rtrtr.conf", "644"],
    ["debian/service.preset", "/lib/systemd/system-preset/50-rtrtr.preset", "644"],
]
maintainer-scripts = "debian"
changelog = "debian/changelog" # this will be generated by the pkg workflow
copyright = "Copyright (c) 2021, NLnet Labs. All rights reserved."
conf-files = ["/etc/rtrtr.conf"]
systemd-units = { unit-name = "rtrtr", enable = false }

[package.metadata.deb.variants.minimal]

